name: 'Setup Build'
description: 'Setup for Build'
inputs:
  google-services:
    description: 'Google Services'
    required: true

runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create google-services.json
      shell: bash
      run: echo -n "${{ inputs.google-services }}" | base64 --decode > ./app/google-services.json

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
