apply plugin: "dagger.hilt.android.plugin"
apply plugin: "com.google.devtools.ksp"

android {
    hilt {
        enableAggregatingTask = true
    }
}

dependencies {
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    testImplementation libs.hilt.android.testing
    kspTest libs.hilt.compiler
}

androidComponents {
    onVariants(selector().all(), { variant ->
        afterEvaluate {
            def capName = variant.name.capitalize()
            def kspTask = tasks.findByName("ksp${capName}Kotlin")
            if (kspTask != null) {
                def protoTask = tasks.findByName("generate${capName}Proto")
                if (protoTask != null) {
                    kspTask.setSource(protoTask.outputs)
                }

                def wireTask = tasks.findByName("generate${capName}Protos")
                if (wireTask != null) {
                    kspTask.setSource(wireTask.outputs)
                }
            }
        }
    })
}
