name: code-review

permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    name: Code Review By Chatgpt
    runs-on: ubuntu-latest
    steps:
      - name: CodeReview
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
