name: develop-merge

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Check Build Test
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Setup For Build
      uses: ./.github/actions/setup
      with:
        google-services: ${{ secrets.GOOGLE_SERVICES }}
        keystore: ${{ secrets.KEYSTORE }}
        keystore-properties: ${{ secrets.KEYSTORE_PROPERTY }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :app:assembleDebug
