name: pull-request

on:
  merge_group:
  pull_request:
    branches: [ "develop" ]

jobs:
  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@master
        with:
          configuration-path: '.github/assign_config.yml'

  build:
    name: Check Build Test
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Setup For Build
      uses: ./.github/actions/setup
      with:
        google-services: ${{ secrets.GOOGLE_SERVICES }}
        keystore: ${{ secrets.KEYSTORE }}
        keystore-properties: ${{ secrets.KEYSTORE_PROPERTY }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :app:assembleDebug

  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter
